sudo: true
language: generic
dist: trusty
group: travis_latest

env:
  global:
  - DOCKER_BASE_TAG=3.7-ubuntu-16.04
  - DOCKER_BASE_IMAGE=zerocci/ice-base:${DOCKER_BASE_TAG}
  - DOCKER_BUILD_IMAGE=zerocci/ice-travis-build:${TRAVIS_BUILD_NUMBER}
  - MAKEFLAGS="-j3 V=1 OPTIMIZE=no USER_NAMESPACES=no CONFIGS=shared"
  - DOCKER_RUN="docker run --rm ${DOCKER_BUILD_IMAGE} /bin/bash -c"
  - ALLTESTS="python allTests.py --protocol=ssl --workers=4"

jobs:
  include:
    - stage: build docker image
      script:
      - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
      - |
        echo "FROM ${DOCKER_BASE_IMAGE}" >> Dockerfile
        echo "RUN make ${MAKEFLAGS}" >> Dockerfile
      - docker build --cache-from ${DOCKER_BASE_IMAGE} -t ${DOCKER_BUILD_IMAGE} .
      - docker push ${DOCKER_BUILD_IMAGE}

    - stage: test docker image
      script: $DOCKER_RUN "${ALLTESTS} --filter=cpp"
      env: TESTING=C++
    - script: $DOCKER_RUN "cd cpp; make ${MAKEFLAGS} CONFIGS='shared cpp11-shared'; ${ALLTESTS}"
      env: TESTING=C++11
    - script: $DOCKER_RUN "${ALLTESTS} --filter=java"
      env: TESTING=Java
    - script: $DOCKER_RUN "${ALLTESTS} --filter=java-compat"
      env: TESTING=Java Compat
    - script: $DOCKER_RUN "${ALLTESTS} --filter=js"
      env: TESTING=JavaScript
    - script: $DOCKER_RUN "${ALLTESTS} --filter=php"
      env: TESTING=PHP
    - script: $DOCKER_RUN "${ALLTESTS} --filter=python"
      env: TESTING=Python
    - script: $DOCKER_RUN "${ALLTESTS} --filter=ruby"
      env: TESTING=Ruby

notifications:
  email: travis-ci@zeroc.com
  slack:
    secure: TywLzzH1Hx3Pb5I4s4wxbEZ9nOAPkamZDqHBOkpLSNSRa2iSk6n5GcQi5bnw0Ct59oTEytO/8fNP6mYwf5G2rrXGWpcdgSdyLMcUk6ASeO7ANv7xLKhVWbbOoVuZxFJvIG5mTYpCa3R58EtchQErzdyf3rRMN3rq/ZBmocFMcRY=
